version: "3"

tasks:
  # ==========
  # Terraform
  # ==========

  plan-infra:
    dir: infra
    desc: Plan infra
    cmds:
      - terraform plan -var-file="../.tfvars"

  apply-infra:
    dir: infra
    desc: Apply infra
    cmds:
      - terraform apply -var-file="../.tfvars"
